//
// Created by mor on 1/13/23.
//

#ifndef KNN_CLASSIFICATION_SERVER_OPTIONTHREE_H
#define KNN_CLASSIFICATION_SERVER_OPTIONTHREE_H


class OptionThree {

};


#endif //KNN_CLASSIFICATION_SERVER_OPTIONTHREE_H
