//
// Created by mor on 1/13/23.
//

#ifndef KNN_CLASSIFICATION_SERVER_OPTIONEIGHT_H
#define KNN_CLASSIFICATION_SERVER_OPTIONEIGHT_H

class OptionEight {

};

#endif //KNN_CLASSIFICATION_SERVER_OPTIONEIGHT_H
